### ISSUE TITLE
ExprAdapter decoder error

### ISSUE THREAD

**Issue by horshine** [construct/construct#721]
```py
In [35]: construct.__version__
Out[35]: '2.9.45'

from construct import *
iec_104 = Struct(
    "iec104",
    Const(b"\x68"),
    "length" / Byte,
    ExprAdapter(
        "APCI1" / Int16ul,
        encoder=lambda obj, ctx: obj if obj == "S" else obj << 1,
        decoder=lambda obj, ctx: obj >> 1 if obj & 1 == 0 else "S" ,
    ),
    ExprAdapter(
        "APCI2" / Int16ul,
        encoder=lambda obj, ctx: 0 if obj is None else obj << 1,
        decoder=lambda obj, ctx: obj >> 1 ,                                    // this  line error              
    ),
)

File "C:\Users\tester\Desktop\untitled-3.py", line 17, in <module>
  decoder=lambda obj, ctx: obj >> 1 ,
File "C:\Anaconda2\Lib\site-packages\construct\core.py", line 1963, in __init__
  self.subcons = mergefields(*subcons)
File "C:\Anaconda2\Lib\site-packages\construct\core.py", line 196, in mergefields
  if sc.flagembedded:

AttributeError: 'str' object has no attribute 'flagembedded'
```

**Comment by horshine** [comment]
I also run it  in construct version 2.8.16, it works, no errs.
anyone could explain it ,thanks

**Comment by arekbulski** [comment]
Struct field "iec104" is just wrong. "APCI" should name adapters, not the subcons inside of them. I dont believe that putting a string instead of a class in a Struct works in any 2.8 version.

**Comment by horshine** [comment]
thank you, I'm new on construct. 
That code I copy from other repo that used construct vesion 2.5,
thank you for your answer.
