### ISSUE TITLE
parse_stream - AttributeError: 'str' object has no attribute '_parse'

### ISSUE THREAD

**Issue by latot** [construct/construct#454]
Hi all!, well i'm trying to use this, i'm trying to pass from 2.5 to 2.8, so i can have some mistakes (and i'm new in this), anyway, my problem is with the function parse_stream, because always send the same error, i'm calling it from a Struct, here is the code:

```
with open(os.path.join(d, 'stitem.gbin')) as item_file:
    item_db = GBNLFormat(ItemModel).parse_stream(item_file)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/pipe/.local/lib64/python2.7/site-packages/construct/core.py", line 201, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/home/pipe/.local/lib64/python2.7/site-packages/construct/core.py", line 993, in _parse
    subobj = sc._parse(stream, context, path)
AttributeError: 'str' object has no attribute '_parse'
```
code from nepugia project:

This is from python 2.7

Thx.

**Comment by arekbulski** [comment]
Wrong variable? :blush: 
```py
>>> with open(dfile) as item_file_:
...     db = GBNLFormat(ItemModel).parse_stream(item_file_)
```

**Comment by latot** [comment]
same result D: (my wrong when i copy the code here), lets copy the original code from nepugia project:

```
with open(os.path.join(d, 'stitem.gbin')) as item_file:
    item_db = GBNLFormat(ItemModel).parse_stream(item_file)
```

:D Thx!

**Comment by arekbulski** [comment]
parse_stream calls _parse method on self, so GBNLFormat(ItemModel) seems to be a string and not a construct instance. This problem is not an issue with this library at all.

**Comment by latot** [comment]
mmm, 

```
>>> type(GBNLFormat(ItemModel))
<class 'construct.core.Struct'>
```

**Comment by arekbulski** [comment]
Huh, I am intrigued. Please link me a source with the line where GBNLFormat is defined?

**Comment by latot** [comment]
Hi, this file only have the GBNL:
https://github.com/latot/python-nepugia/blob/nn/nepugia/formats/gbnl.py

Thx.

**Comment by latot** [comment]
the nepugia project works fine with 2.5, now moving to 2.8 i see this.

**Comment by arekbulski** [comment]
Its obvious (to me), Struct first subcon is a string, not a construct. It seems that either you have no idea how Construct works at all or you are familiar with ancient 2.5 version. You should read the entire docs and simply learn how to use it (or just read the transition chapter but I recommend reading entire thing). 
https://construct.readthedocs.io/en/latest/index.html
https://construct.readthedocs.io/en/latest/transition28.html

**Comment by latot** [comment]
:O so finally was my mistake, thx for your help, i'll read the docs deeper.

Thx!

**Comment by arekbulski** [comment]
Yes, that is probably biggest improvement in 2.8 but so many other things were changed. Porting that project to 2.8 is not merely an issue of naming fields.
