### ISSUE TITLE
ImportError: cannot import name Int16ub

### ISSUE THREAD

**Issue by locurasoft** [construct/construct#393]
Hi!

This is probably just a configuration issue but I am new to python and don't know much about how to debug it.

I am trying to use an application that depends on construct 2.5.2 on a Windows 10 machine.
I have installed construct like this: `pip install c:\construct-2.5.2-py2.py3-none-any.whl`
It seems to have worked as the second time I run the same command I get this message: `Requirement already satisfied: six in c:\tools\python27\lib\site-packages (from construct==2.5.2)`. But I can't find the module in `c:\tools\python27\Lib\`

If I run 
`>>> help("modules")`
I can find the `construct` module among the installed packages.

However, I get an error when I try to run the following command:
```
>>> from construct import Int16ub, Int16ul
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Int16ub
```

Unfortunately I don't know how to debug this further. Any help would be much appreciated.

Thanks!
/Pascal

**Comment by arekbulski** [comment]
2.5 is an ancient version no longer supported, the Int* classes are from 2.8

**Comment by locurasoft** [comment]
Thanks for answering so quickly!

I downloaded that version because I could only find a .whl file there. The other versions are only released as source distributions. Is there any documentation on how to install source distributions somewhere?

BR
/Pascal

**Comment by locurasoft** [comment]
It works fine with version 2.8.12
