### ISSUE TITLE
Naming structs seems to have broken between 2.8 and 2.9

### ISSUE THREAD

**Issue by fake-name** [construct/construct#706]
I'm reinstalling dependencies, and construct seems to have broken naming structs at some point between 2.8 and 2.9.

I have code that looks like:

```
	c.Struct("telemetry",
			"x" / c.Float64n,
			"y" / c.Float64n,
			"distance" / c.Float64n,

			"theta" / c.Float32n,
			"velocity" / c.Float32n,
			"turnRate" / c.Float32n,
			c.Padding(4),

			"timeStamp" / c.Float64n,
		),
```
(where `c` is `import construct as c`).

This seems to no longer work.

Additionally, it fails with a REALLY opaque error:

```
C:\Code\AVMU-Components\applications\Avmu_Applications\PyAvmu_cffi>python main.py
C:\Program Files\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    from lib.datalogging import log_thread
  File "C:\Code\AVMU-Components\applications\Avmu_Applications\PyAvmu_cffi\lib\datalogging\log_thread.py", line 10, in <module>
    import lib.datalogging.imb_log
  File "C:\Code\AVMU-Components\applications\Avmu_Applications\PyAvmu_cffi\lib\datalogging\imb_log.py", line 7, in <module>
    from .. import libimb
  File "C:\Code\AVMU-Components\applications\Avmu_Applications\PyAvmu_cffi\lib\libimb\__init__.py", line 2, in <module>
    from .parse import *
  File "C:\Code\AVMU-Components\applications\Avmu_Applications\PyAvmu_cffi\lib\libimb\parse.py", line 5, in <module>
    from . import data_parse
  File "C:\Code\AVMU-Components\applications\Avmu_Applications\PyAvmu_cffi\lib\libimb\data_parse.py", line 62, in <module>
    "rx_p" / c.Int32sn,
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 1957, in __init__
    self.subcons = mergefields(*subcons)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 194, in mergefields
    if sc.flagembedded:
AttributeError: 'str' object has no attribute 'flagembedded'

```

Being able to attach readable names to structs is **extremely** valuable for handling extremely large, complicated structures. I'm not sure why it's now missing, but it definitely should come back, even if only as a keyword argument.

The above code works with 2.8. Looking at the "Transition to 2.9" page, I don't see any mention of these changes.

**Comment by arekbulski** [comment]
The reason is obvious. Construct does not use parameters for naming fields. Operator / was introduced in early 2.8 versions, like 2 years ago. The code you shown is by any measure, ancient.
```py
c.Struct("telemetry", ...)
"telemetry" / Struct(...)
```

**Comment by arekbulski** [comment]
Okay, I completely missed the point. You are already using / operator for naming fields but also using first parameter for naming the struct. That syntax was deprecated like 2 years ago. You can name the struct the same way you name fields, like `'name'/Struct(...)`.

**Comment by fake-name** [comment]
> You can name the struct the same way you name fields, like 'name'/Struct(...).

Oh wow, it's that obvious? Derp.

**Comment by arekbulski** [comment]
The / operator works on any Construct instance. If you nest a struct inside a struct, how else would you name it? This is funny but people so often name Structs and make me complain about it. You should only be naming fields inside a Struct. There is no point naming Structs themselves, nor embedded Structs.

**Comment by fake-name** [comment]
> There is no point naming Structs themselves, nor embedded Structs. In those two cases the names are just ignored.

I couldn't possibly disagree more strongly. Naming structs is incredibly useful for making your code understandable and self documenting.

**Comment by arekbulski** [comment]
No, I encountered on many occasions people writing:
```py
RequestResponse = "request_response" / Struct(...)
Message = "message" / Struct("request_response" / RequestResponse, ...)
```

**Comment by fake-name** [comment]
Ok, that's legit pretty dumb.
